### ISSUE TITLE
v1.2.0 release checklist

### ISSUE THREAD

**Issue by Thundo54** [Thundo54/tablice-td2#6]
- [x] STS => tablice-td2 (in menu footer)
- [x] Tablice Stacyjne => Tablice Zbiorcze [station_name] (page header)
- [x] mobile.scss fix
